[package]
name = "kumarion/timercountdown"
description = "A timer/countdown combo that can be used to time events or countdown to events."
version = "0.0.6"
license = "MIT"
authors = ["Kumarion (https://github.com/Kumarion)"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Signal = "sleitnick/signal@^1"