[package]
name = "kumarion/quicktween"
description = "Makes tweening quick and easy by creating and automatically destroying tweens when they are done."
version = "0.0.1"
license = "MIT"
authors = ["Kumarion (https://github.com/Kumarion)"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"