[package]
name = "kumarion/richify"
description = "A simple library to assist RichText rendering in Roblox."
version = "0.0.1"
license = "MIT"
authors = ["Kumarion (https://github.com/Kumarion)"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"